# Stage 1: Build the React application
FROM node:22-alpine as build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./ # Or yarn.lock
RUN npm install # Or yarn install

COPY . ./

RUN npm run build # Or yarn build

# Stage 2: Serve the built application with Nginx
FROM nginx:alpine

# Copy the Nginx default configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built React app from the build stage
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]