
version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: FixItFastDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    container_name: fixitfast_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/FixItFastDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

    depends_on:
      db:
        condition: service_healthy



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    container_name: fixitfast_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  pgdata:


